// Generated by CoffeeScript 1.9.3
(function() {
  var MongoClient, ObjectId, assert, bodyParser, clicolour, cookieParser, express, favicon, logger, mongoose, passport, passporthttp, passportlocal, path, routes, users;

  express = require('express');

  path = require('path');

  bodyParser = require('body-parser');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  passport = require('passport');

  passportlocal = require('passport-local');

  passporthttp = require('passport-http');

  routes = require('../routes/index');

  users = require('../routes/users');

  mongoose = require('mongoose');

  MongoClient = require('mongodb').MongoClient;

  assert = require('assert');

  ObjectId = require('mongodb').ObjectID;

  clicolour = require('cli-color');

  exports.stadaradconnect = function(x) {
    var url;
    url = 'mongodb://localhost:27017/web-os';
    return MongoClient.connect(url, function(err, db) {
      assert.equal(null, err);
      console.log(clicolour.cyanBright("webOS ") + clicolour.magentaBright("database ") + "Connected correctly to mongo server.");
      return db.close();
    });
  };

  exports.connect = function() {
    var db;
    mongoose.connect('mongodb://localhost:27017/connections');
    db = mongoose.connection;
    db.on('error', console.error.bind(console, 'connection error:'));
    return db.once('open', function(callback) {
      return console.log(clicolour.cyanBright("webOS ") + clicolour.magentaBright("database ") + "Yay! We succefully connected to the db");
    });
  };

}).call(this);
